### ISSUE TITLE
Ubuntu 15.04 Terminal Issue

### ISSUE THREAD

**Issue by canibal** [Cairo-Dock/cairo-desklet#1]
When I open the terminal, after upgrading to the new version of Ubuntu, the terminal window opens and then closes/disappears right away. Not sure if the process is still running in the background once opened, but if so, then that would be problematic. Any advice?

**Comment by matttbe** [comment]
Hello,

Do you have a problem with Cairo-Dock's Terminal applet or GNOME's Terminal application?
If yes, please report this bug to Cairo-Dock/Glx-Dock's forum or Launchpad ;-)
